### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by rotnicki** [daattali/beautiful-jekyll#1082]
Does Beatiful Jekyll support localization - translation - of the interface into other languages then English?
If so then how to do it?
If not then it is a requested feature.

**Comment by daattali** [comment]
Unfortunately there's no simple system for that in jekyll, so this theme does not support that out-of-the-box. If you google for "jekyll i18n" (i18n stands for internationalization) you'll find different blog posts and projects that aim for this, and if you have the technical aptitude for it you'll be able to add it to your site, it would require local build rather than github build. I'm sorry but I can't help further with this.
