### ISSUE TITLE
Can anyone add staticman comment system?

### ISSUE THREAD

**Issue by vietanhdev** [daattali/beautiful-jekyll#115]
Hello, I've found a wonderful static comment system Staticman ([https://staticman.net/](https://staticman.net/)). Can anyone add it to our Beautiful Jekyll? :D Thank you very much!

**Comment by daattali** [comment]
beautful jekyll already supports a very powerful and very popular comment system called Disqus. It's extremely easy to enable it on your site and it's used by thousands and thousands of people so you can be assured it works well. I don't see why a different comment system that's fairly unknown and untested should be supported when disqus already works?

**Comment by vietanhdev** [comment]
But there are many people (including me) from my country - Viet Nam having problem with disqus comment system. Maybe Disqus is blocked by some ISPs? And I think it also happens on other countries.

Further more, with Staticman commenting system, we can keep all comments in Github repository instead of have them stored in Disqus server. Many people will love it.

**Comment by daattali** [comment]
You're right, I had no idea Disqus is blocked there. Anyway, I just looked at staticman and it looks like if you want to use it, you'll just need to add it manually yourself. There isn't much to add to the template in order to support it because it has different implementations depending on your use case. So all you need to do is to follow their instructions, but I don't think it can be generalized into a theme

**Comment by vietanhdev** [comment]
Ok. thank you.

**Comment by VincentTam** [comment]
@daattali As an Octopress and Disqus user for three years (my GitHub Pages), I can provide another rationale for @vietanhdev's request for Staticman support.  I suffered from the URL change after switching timezone.  I tried refactoring the comment paths on Disqus's online platform, but the embedded box in my old blog still display the wrong hyperlinks.

More importantly, under Disqus's model, every time a page with Disqus comments is loaded, one has to wait for Disqus's response.
Provided that the blog receives comments occasionally, Staticman fits the needs of blog owners better than Disqus in terms of SEO and load speed.

Nonetheless, thx @daattali for this great theme based on which Beautiful Hugo is created.

@vietanhdev The later theme has native Staticman support, so you may consider switching to Hugo, which is powered by Go.  Golang is much faster than Ruby.  I used to wait for a minute for my old Octopress 2.0 blog with over 300 articles.  Last week, I published halogenica/beautifulhugo#222 for Staticman's nested comment support.  If you want to stick with Jekyll, you may see the theme Minimal Mistakes for implementing Staticman in a Jekyll theme (or a simpler example git.io/smdemo that I created last month).

**Comment by daattali** [comment]
@VincentTam I would be happy to accept a PR to support staticman if you,  or anyone else, would like to add it

**Comment by VincentTam** [comment]
@daattali I'll look into this after exams in two weeks, but I don't actually know Jekyll's template code (nor CSS), so it's possible that I end up without success like my feedback to halogenica/beautifulhugo#226.

Unlike my PR for Beautiful Hugo, I'll separate this support into two PRs (one for Staticman support and another one for Markdown preview) since they involve different technologies.  For debug, there's no reason to bundle them together.

For the first proposed PR, I'll try to port the code from my recent PR.  Since I'm not a developer, I will neither go deep into Staticman's authenticated comments  (I've tested them in early September though.); nor test the lastest eduardoboucas/staticman#231. (These functionalities were great PRs by Nicholas Tsim, and @staticmanlab supports this though.)  To show Staticman's GitLab support, which is *the* goal of writing my recent PR, I'll break the form action URL into several parameters in the theme's site config file, such as Git service provider, user name, repo name, etc.

For the second one, you may drop this if you don't like.  Users will be able to switch this off in config, but I leave it on by default to reduce Markdown syntax error in comments.  I don't know if Showdown's GFM option matches Jekyll's flavor of Markdown syntax.  Showdown is just one example.  What do you think?

**Comment by VincentTam** [comment]
Agreed.

**Comment by VincentTam** [comment]
Sorry @vietanhdev @daattali I'm abandoning this unless I found a way to get this to [get this work on GitLab](https://gitlab.com/VincentTam/beautiful-jekyll/-/jobs/134051594).  I imported this repo to GitLab, did the site config on a `gl-pages` branch and added the generated `.gitlab-ci.yml`, but I received a [runtime error](https://gitlab.com/VincentTam/beautiful-jekyll/-/jobs/134051594).

```
$ bundle exec jekyll build -d public
Configuration file: /builds/VincentTam/beautiful-jekyll/_config.yml
            Source: /builds/VincentTam/beautiful-jekyll
       Destination: public
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    Invalid US-ASCII character "\xE2" on line 5
jekyll 3.7.4 | Error:  Invalid US-ASCII character "\xE2" on line 5
ERROR: Job failed: exit code 1
```

From the last few lines of the error message, it seems that this error has nothing to do with my configurations.  Given that I've already built several testing GitLab Pages (including [GitLab + Staticman + Jekyll](https://vincenttam.gitlab.io/gl-jekyll)), I think I'm abandonning this since I've already shown that Staticman works with GitLab, which is open-source unlike GitHub.

**Comment by VincentTam** [comment]
Update:

1. I've already eaten my words by providing a PR.
2. I've eaten my words again by creating a GitLab demo site with this theme in #510.
