### ISSUE TITLE
{desc} hover on search results?

### ISSUE THREAD

**Issue by michael-b-jordan** [daattali/beautiful-jekyll#1156]
When you hover over search results, it just says {desc}, is this a issue or?
![image](https://github.com/daattali/beautiful-jekyll/assets/129551266/63000897-76f6-4153-8013-bcd3b23ade5c)

Do you also know the location or where I can edit the design of the search bar in the source files? Much appreciated, thanks.

**Comment by Fatboi88** [comment]
I’m really horny

**Comment by daattali** [comment]
Looks like it's a bug with the search library. We're using this library: https://github.com/christian-fei/Simple-Jekyll-Search 
Here's a demo from the author: https://christian-fei.github.io/Simple-Jekyll-Search/ you can see that even in their demo this happens. Unfortunately it seems like the author of that library stopped supporting this library, so I doubt it'll get fixed.

Within beautiful-jekyll, [this](https://github.com/daattali/beautiful-jekyll/blob/master/_includes/search.html) is where that code is being used. I'm closing this issue since the {desc} issue is with the third party library.

**Comment by daattali** [comment]
Actually from looking at the library's code, I was able to figure out how to fix the problem. It's not documented, but it was still an easy fix.  https://github.com/daattali/beautiful-jekyll/commit/5d009e879929ad0be6453a1a41bdf3226781a96f

**Comment by Fatboi88** [comment]
Really

**Comment by daattali** [comment]
You'll have to update your site to include the latest version, it doesn't happen automatically. See example https://daattalitest.github.io/
