### ISSUE TITLE
[BUG] Search JSON doesn't escape back slashes and breaks search

### ISSUE THREAD

**Issue by monksy** [daattali/beautiful-jekyll#1279]
https://github.com/daattali/beautiful-jekyll/blob/e5ababbfb57c0dbf5dae997c60271b4ccee6fed8/_includes/search.html#L14

This should be able to escape back slashes in the title. Since it doesn't, this creates invalid json and breaks the parsing:

Example: 

```json
  {
    "title": "Today I learned: Use %n rather than \n in String.format",
    "category": "",
    "url": "/blog2/2013/11/27/today-i-learned-use-n-rather-than-n-in-string-format/",
    "date": "November 27, 2013"
  },
```
Produces: SyntaxError: JSON.parse: bad control character in string literal

**Comment by daattali** [comment]
Thanks for the report. I'm surprised by this bug, because the title does get escaped. Most other characters seem to be correctly escaped, but it looks like a backslash needs to be escaped manually with another backslash (using `\\` works fine according to my test). Do you agree this looks like a bug with the escape filter in jekyll/Liquid template, rather than a bug in the theme?

**Comment by daattali** [comment]
@monksy are you able to test to see whether this is a bug resulting from this theme or not?

**Comment by monksy** [comment]
The issue is due to the liquid filters that you're using do not fix the \ character usage.  That causes downward issues when trying to parse out the JSON. I provided an example that will break the theme.

**Comment by daattali** [comment]
Fixed
