### ISSUE TITLE
Stackoverflow icons not working as expected

### ISSUE THREAD

**Issue by isomerase** [daattali/beautiful-jekyll#15]
Adding  `stackoverflow: my-SO-name` and `  stackoverflow: true` to `footer-links-active` inside `_config.yml` does not work as expected because the baseURL for network profiles looks like `www.stackoverflow.com/users/#######/my-SO-name` (rather than `www.stackoverflow.com/my-SO-name`).

As a temporary solution, I set `stackoverflow` to `#######/my-SO-name` and edited `<a href="https://stackoverflow.com/{{ site.author.stackoverflow }}"` to include `/users/` inside `_includes/footer.html`

**Comment by daattali** [comment]
Yes I'm aware of that, LinkedIn also has a similar problem. That's why the demo config value is `stackoverflow: yourlink  # eg. "users/3943160/daattali"`

Although you're right that I could remove "users" from there and make that hardcoded, I might do that, but you'd still have to provide both the numeric id and username unfortunately.

**Comment by daattali** [comment]
By the way, I'd really appreciate if you kept the small attribution to this theme in the footer, or at least somewhere

**Comment by isomerase** [comment]
Ah, I forked my site from one of your [featured user's site](thomased.github.io) so I never saw the demo config. They also scrubbed the attribution, I'll make sure to add it back in. Thanks for this theme!

**Comment by daattali** [comment]
No worries, it's obviously not mandatory (he put an attribution in the about page btw)

Thanks for the bug reports
