### ISSUE TITLE
"forking" updates (?)

### ISSUE THREAD

**Issue by b1azk0** [daattali/beautiful-jekyll#162]
Hello there, 
1st of all, sorry if this question ends up being stupid.

I'm using this theme at my github.io page but I was wondering what should I do (if anything at all) to take advantage of updates made in this original repo?

Clearly I don't fully understand how forking etc works but I also coudn't find any answer.
Thank you and best regards!

**Comment by daattali** [comment]
Not a silly question at all. I'm actually surprised not more people ask.
Unfortunately I don't have a solution that I personally recommend since I
never have to do it, but it is a common enough question that others have
talked about it. GitHub has an official help page for this topic that might
be useful: https://help.github.com/articles/syncing-a-fork/

But that help page requires you to use git locally via command line, which
isn't ideal for many people who use Beautiful Jekyll. If you want to do it
all quickly from within the GitHub web interface, I found this webpage
(haven't tried it myself, but it looks legit - if you try it please let us
know if it worked!) https://www.sitepoint.com/quick-tip-sync-your-fork-with-
the-original-without-the-cli/


Hello there,
1st of all, sorry if this question ends up being stupid.

I'm using this theme at my github.io page but I was wondering what should I
do (if anything at all) to take advantage of updates made in this original
repo?

Clearly I don't fully understand how forking etc works but I also coudn't
find any answer.
Thank you and best regards!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/daattali/beautiful-jekyll/issues/162>, or mute the
thread

**Comment by daattali** [comment]
Not a silly question at all. I'm actually surprised not more people ask.
Unfortunately I don't have a solution that I personally recommend since I
never have to do it, but it is a common enough question that others have
talked about it. GitHub has an official help page for this topic that might
be useful: https://help.github.com/articles/syncing-a-fork/

But that help page requires you to use git locally via command line, which
isn't ideal for many people who use Beautiful Jekyll. If you want to do it
all quickly from within the GitHub web interface, I found this webpage
(haven't tried it myself, but it looks legit - if you try it please let us
know if it worked!) https://www.sitepoint.com/quick-tip-sync-your-fork-with-
the-original-without-the-cli/

**Comment by b1azk0** [comment]
Thanks for the link.
Unfortunately i got stuck at step 2:

![2017-01-25 09_11_10-comparing daattali_master b1azk0_master daattali_beautiful-jekyll](https://cloud.githubusercontent.com/assets/22635132/22282698/6ed0b6ba-e2de-11e6-96fc-49f65f26a087.png)

I'll try original command line method but for some reason I sense same problems.

**Comment by b1azk0** [comment]
Ok, I noticed (in screenshot above) that I didnt change bases as per instruction.
Fixed that and tried again. Here is an other error:
![2017-01-25 11_57_55-sync changes in original repo test by b1azk0 pull request 1 b1azk0_b1azk0](https://cloud.githubusercontent.com/assets/22635132/22288104/b9e7f642-e2f5-11e6-85af-cbd8af80db42.png)

**Comment by daattali** [comment]
Ah looks like this method WOULD work if there were no files that we both touched. But those two specific files have been updated by both of us and githu doesn't know what to do. There might be a way to do a merge from github,  but if not then you would have to reort to command line to fix the merge conflict...

**Comment by b1azk0** [comment]
Is there an straightforward way to revert the changes I made to these two files?
While index.html is in my repository, the "first post" md file is gone and has been since day 1 of my blog.
Sorry for taking your time with probably basic stuff

**Comment by daattali** [comment]
Through the web interface, I don't know how to do that. Git is not as
simple as it should be :(

**Comment by b1azk0** [comment]
ok, ill try to follow command line instructions and will report back.
worst case scenario: i can keep my blog md files and start the blog from scratch. After all its only 2 posts long :)

**Comment by daattali** [comment]
Yes that's actually probably the easiest (but not "correct") solution. With
git I often find myself doing these "burn it all down, start again" approach

**Comment by daattali** [comment]
By the way, this theme is fairly mature by now and stable, so it's very rare that I'll update any files that you also update locally. In the future it should be a smooth process to sync from github, and also don't expect too frequent future updates

**Comment by b1azk0** [comment]
I reforked jekyll from scratch and set it up with old config files.
Now it looks like future updates (coming or not) should be possible.

![2017-01-26 13_48_29-comparing b1azk0_master daattali_master b1azk0_b1azk0 github io](https://cloud.githubusercontent.com/assets/22635132/22331889/31b70c98-e3ce-11e6-87ec-ec813a61c6ad.png)
Regards
