### ISSUE TITLE
bigimg text overlay doesn't scale down properly to below 365px width

### ISSUE THREAD

**Issue by AlanBarber** [daattali/beautiful-jekyll#166]
I've noticed that when using the bigimg it doesn't scale down below 365px width. the text overlay drops below the image instead. you can see this on your own personal site if you use chrome tools and select the mobile small (320px) view window.

**Comment by daattali** [comment]
That was done on purpose. It wasn't like that initially, but on small screens the background was pretty much useless because the text would cover it all, so in order to actually have an image I decided to move the text below it on narrow screens. That's totally a personal design decision I'm not claiming it's right or wrong. But I don't think I'm going to change it in the theme. If you don't want that behaviour you can find the CSS for it and remove it, it should be in the main.css file
