### ISSUE TITLE
main.css is not up-to-date?

### ISSUE THREAD

**Issue by moreplavec** [daattali/beautiful-jekyll#168]
I'm trying to create Wordpress theme based on your beautiful-jekyll. All looks fine, but there are differences between your blog and github version. For example github version of main.css doesn't contain .paper definitions. Are you going to update github version? Or can I use your blog version of css?

Thanks for your time and good theme!

**Comment by daattali** [comment]
My personal website has lots of things that aren't in this theme. I forked
beautiful jekyll when I started my website, and since then the two have
diverged. When there's anything that I think would be useful to the general
public, I add it to the theme as well. For example, big images didn't used
to be supported, until enough people told me they want to copy it from my
site. So if there's anything you see on my personal website that doesn't
exist in beautiful jekyll, please let me know and if I or others agree then
I'll port it. In the meanwhile, feel free to go to my personal website's
source code and copy things over :)

---
R-Shiny Consultant
http://deanattali.com/shiny

**Comment by moreplavec** [comment]
Thanks for info and so quick response.
