### ISSUE TITLE
Footer contact links don't display in text-only browser

### ISSUE THREAD

**Issue by gabeguz** [daattali/beautiful-jekyll#176]
Tested with lynx (and links).  The \<li>'s that contain the github, twitter, etc links in the footer display no information in a text only browser. 

Steps to reproduce: 

```
$ lynx  http://deanattali.com/beautiful-jekyll/
```

hit `space bar` until you are at the bottom of the page, and notice there are 4 `*`'s that appear where the contact links should be.

**Comment by daattali** [comment]
I have to admit I've never used a text only browser, so I had no idea. This issue makes sense to me because I'm using fontawesome icons, so they have no text, and they're not images so there's no alt text. If you have experience with such browsers, do you know what the standard fix for such things is?

**Comment by gabeguz** [comment]
I see some ideas on the font awesome website.  I'll find one that works well for me and submit a PR.  Thanks.

**Comment by daattali** [comment]
Thank you!

---
Founder & Lead Consultant
AttaliTech Ltd
http://deanattali.com/shiny

**Comment by eugenius1** [comment]
I've just submitted a PR, adding `class="sr-only"` to both the footer and share buttons

**Comment by gabeguz** [comment]
Nice, confirmed, works for me!
