### ISSUE TITLE
image of YAML front matter

### ISSUE THREAD

**Issue by aquynh** [daattali/beautiful-jekyll#208]
i use "image" parameter for my posts, but there is one issue: the picture is automatically cropped, that in the way i dont really want.

is there any way to control how the picture is cropped, on the size of the picture in the post excerpt, and the size inside the post? if not, what is the recommended size of the original picture?

thanks.

**Comment by daattali** [comment]
It's impossible to have a perfect picture because each screen will display
it differently. I think the browser tries to place the picture centered.
Try making the browser smaller and slowly increase the window width, you'll
see they the image keeps changing. Because of that it's impossible to find
one perfect size that will work always, you just have to experiment and  see

**Comment by aquynh** [comment]
i see. then another questions: is it possible to have an option to tell Jekyll to keep the image as is (ie. dont crop it), but just scale it up/down to xx%?

**Comment by daattali** [comment]
You can probably play around with the CSS to change exactly how the image is rendered. For example look at https://github.com/daattali/beautiful-jekyll/blob/master/css/main.css#L427 if you remove the `center center` then the image won't be centered.
