### ISSUE TITLE
Hide avatar on small screens

### ISSUE THREAD

**Issue by mstrimas** [daattali/beautiful-jekyll#22]
Hey Dean, 

Thanks for the awesome theme!

I'm finding that the avatar covers up my name on small screens (i.e. on mobile). I notice the avatar decreases in size below a certain resolution, is there a simple way to totally hide it?  

Example: http://quirktools.com/screenfly/#u=http%3A//strimas.com&w=320&h=568&a=37&s=1&p=1  

Thanks!  

M

**Comment by daattali** [comment]
Great link, I love when people submit an issue and I don't have to jump hoops to understand the problem.

I can't test any of this right now because I'm out of the country , but I can think of 3 options:

- You can just remove the `avatar` parameter in `_config.yml` and then it won't show at all
- You can try playing with the CSS if you want to just move it down, but you'll have to figure that out yourself
- You can add some CSS so that only on small screens the avatar is hidden.  Something like this should work (it's not tested, it might work as-is and if not it's probably very very close):
```

@media only screen and (max-width: 500px) {
  .avatar-container {
    display: none;
  }
}
```

I see you bought yourself a domain :+1: 

Please close this issue when you solve your problem

**Comment by mstrimas** [comment]
Thanks, that bit of CSS worked perfectly!
