### ISSUE TITLE
Recommendation for bigimg size?

### ISSUE THREAD

**Issue by OCram85** [daattali/beautiful-jekyll#221]
Hi folks,
do you have any recommendations for the feature images (bigimg) size?

I would like to use the `bigimg` pictures for my posts, but I can't work out a useful height or width standard :cry:

**Comment by daattali** [comment]
There isn't a one size fits all solution to this, because every person will view your site on a different browser with different dimensions. Some browsers will have very wide aspect ratio, some will be narrower, some will be vertical (such as phones), different phones have different screens, etc. The image will always be centered, so the only tip I can give is that you should make sure the important part of the image is in the middle so that it'll always show. Other than that, every browser will show a different clipping of the image...

**Comment by OCram85** [comment]
Thank you  for the quick reply!
