### ISSUE TITLE
[Question] Do you have any plans upgrading to Bootstrap 4?

### ISSUE THREAD

**Issue by OCram85** [daattali/beautiful-jekyll#244]
I was just wondering if you have any plans to upgrade to Bootstrap 4 some day.

**Comment by daattali** [comment]
This was not a pressing issue for me, I had no plans to migrate until it becomes the common standard for most websites. I'd rather wait a bit longer, they removed support for older browsers and I'd rather be conservative and not break anything rather than change early. Are there any strong reasons for me to make the upgrade sooner?

**Comment by OCram85** [comment]
Well, I was working on some card designs like discussed in #238.
But it didn't work out. So I thought it maybe could be easier building it with bootstrap 4.

**Comment by daattali** [comment]
Right, cards are indeed one of the biggest changes from a user's perspective so for your specific case it would help. I don't think at this point I'm ready to migrate yet, but I wouldn't get offended if you import bootstrap 4 instead of 3 in your fork since you need it :)

**Comment by OCram85** [comment]
You're right. I've already thought about this. But I really would like to use your well approved standards. :)

**Comment by daattali** [comment]
I have very different standards when it comes to my own thing that nobody
sees vs a repo that thousands of people use. In my own personal website,
which is a fork of this theme, I do things that I wouldn't want to put
inside the theme, because I try to keep it very conservative and clean and
simple. But if I needed cards on my site, I would without hesitation do the
switch, because it would only affect me, I wouldn't have to worry about
whether it works for everyone else. Go for it!

---
Dean Attali
President & CEO
AttaliTech Ltd
http://AttaliTech.com <http://attalitech.com>

**Comment by daattali** [comment]
Closing because I'm fairly set on not upgrading at the moment :)
