### ISSUE TITLE
Problem con image: and bigimg:

### ISSUE THREAD

**Issue by marste** [daattali/beautiful-jekyll#249]
If I put the internet link of an image, it only works if the link is in https.
If I put a link in http, this link does not work as it compiles the path with http: // my_domain + linkimage

**Comment by daattali** [comment]
I'm seeing something a bit different.

I just tested it out, and in `image` both http and https work.

In `bigimg`, http works but https doesn't (that's the opposite of what you report). I see the problem in the HTML source code: one `/` from the URL gets truncated, so the URLs end up as `http:/` or `https:/` instead of `//`. Apparently for http that's ok but for https it's not! Will have to look into why that is happening.

**Comment by daattali** [comment]
I found the problem. It's because in some places I explicitly replace `//` with `/` because the image URLs do not expect to receive absolute URLs, they were originally intended to only take in relative paths (I made a bad assumption that images you use are stored locally).

This does need to be fixed, but this also showed me another bug: `image` on the feed page doesn't append `site.baseurl`, so it doesn't work with github project pages, but that's why it does work with absolute URLs, unlike `bigimg`.

All URLs (images and others) need to be made more consistent to avoid such problems in the future.

Thanks for bringing this up.

**Comment by marste** [comment]
Thank you Daattali!
However, I am confident that the problem occurs with url http: // and not https: //
Also look at this example:
[http://marzorati.co/install-tftp-atftp-server-ubuntu-linux/](http://marzorati.co/install-tftp-atftp-server-ubuntu-linux/)
with image:
[https://i.stack.imgur.com/tjSgV.jpg
](https://i.stack.imgur.com/tjSgV.jpg
)
If I put an url with http: //
The path to the image will be: http: //marzorati.cowww.abcde.fg/hi.jpg

**Comment by marste** [comment]
Here is the example of an image: it does not work.
[http://marzorati.co/led-wifi-notebook-blink-debian/](http://marzorati.co/led-wifi-notebook-blink-debian/)
The link of image is: [http://www.capalbio.it/images/wifi.png](http://www.capalbio.it/images/wifi.png)

Many thanks!

**Comment by marste** [comment]
Solved.
Change from file nav.html
<img class="avatar-img" src="{{ site.avatar | prepend: site.baseurl | replace: '//', '/' }}" />
to:
<img class="avatar-img" src="{{ site.avatar }}" />
and:
<img class="avatar-img" src="{{ page.image | prepend: site.baseurl | replace: '//', '/' }}" />
to:
<img class="avatar-img" src="{{ page.image }}" />

**Comment by daattali** [comment]
Yep that would solve it for your case. As I said, I need to work on consolidating the URLs so that they would work for both absolute and relative paths but for your version you can just change it

**Comment by daattali** [comment]
closing this issue because it's part of #254
