### ISSUE TITLE
I follow the 3 step just like the gif you post? But I get the 404 not found, why's that?

### ISSUE THREAD

**Issue by woshichuanqilz** [daattali/beautiful-jekyll#25]

**Comment by woshichuanqilz** [comment]
I know the right URL is like this
http://woshichuanqilz.github.com/lizheblog/

**Comment by woshichuanqilz** [comment]
It seems that I can't find the icon or the style and my page is like this:
how can I fix it? 
![69](https://cloud.githubusercontent.com/assets/11295355/12070190/6b8f6fe4-b0a0-11e5-9ee6-9259385bb79e.png)

**Comment by daattali** [comment]
Did you mean http://woshichuanqilz.github.io/lizheblogbf/ instead of http://woshichuanqilz.github.com/lizheblog/?

It seems to me that you only forked the repository (step 1) but didn't do the next steps of renaming the repository and of modifying the config file to reflect your URL. Please follow the instructions [here](https://github.com/daattali/beautiful-jekyll)
