### ISSUE TITLE
staging area for post

### ISSUE THREAD

**Issue by yonicd** [daattali/beautiful-jekyll#251]
what is the best way to preview a post on the blog without it being public? (sorry if newbie question)

**Comment by marste** [comment]
Copy and paste your code here: [http://prose.io/](http://prose.io/)

**Comment by yonicd** [comment]
thank you, but that i can do w/in github by going to the file itself. I meant to see the post fully rendered in something like a preview area, and when it is ready make it public.

**Comment by yonicd** [comment]
i guess it would be something similar to `blogdown::serve_site`, but that seems hardcoded for only bolgdown projects

**Comment by daattali** [comment]
If you want to make something truly private for the preview, that can only
be done if you install jekyll locally on a unix box. But this theme is
focused on being used directly from github and being fully online so I
personally don't do that. When I want to preview a page before publishing
it, I create it in a temporary page instead of placing it inside the _posts
folder. For example I ofyrn create a test.md file which is technically
public but it doesn't get published in the feed sp nobody knows about it,
and I check deanattali.com/test to see how it comes out. When I'm happy
with it I simply rename the file to move it into the _posts folder. It may
not be ideal but it's simple and works well for my purposes

On Sep 18, 2017 09:25, "yonicd" <notifications@github.com> wrote:

i guess it would be something similar to blogdown::serve_site, but that
seems hardcoded for only bolgdown projects

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/daattali/beautiful-jekyll/issues/251#issuecomment-330219512>,
or mute the thread

**Comment by yonicd** [comment]
got it. thanks!
