### ISSUE TITLE
About page not rendering

### ISSUE THREAD

**Issue by HintikkaKimmo** [daattali/beautiful-jekyll#28]
I am facing following error with about me page. I have updated markdown and it renders fine in hintikkakimmo.github.io, but not when developing locally? 

If I run Jekyll server command and click the link I get 404 error page, if I do the same on the github page it works fine. 

Just in case I did run bundle install, updated bundler, Jekyll build and Jekyll build --watch with no error but serving page locally just does not seem to work. Similar happen with post time to time as well. 

If I look at _site folder I can find properly generated HTML files for both post and aboutme. 

Bundler 1.1.2, Ruby 2.2.1 and Jekyll 2.4.0

**Comment by daattali** [comment]
Hey, I unfortunately can't help with this issue, as I never tried running Jekyll locally. Beautiful Jekyll was built to work well with GitHub Pages because I meant for it to be super simple for anyone to use, including myself. I never wanted to deal with local installations and ruby/gems and all that... I really can't help you here, sorry!

**Comment by HintikkaKimmo** [comment]
Weirdly enough I fixed this by auto indenting HTML on _includes and _layouts folders. Probably a Jekyll bug.

**Comment by daattali** [comment]
Awesome :)
