### ISSUE TITLE
HTML widgett on Jekyll

### ISSUE THREAD

**Issue by abiyug** [daattali/beautiful-jekyll#29]
Hi Dean,
Not able to render HTML widget (ex. DT, Leaflet) on beautiful-jekyll. Here is the YAML 
---
layout: post
title: "HtmlWidge"
author: "Abiyu Giday"
date: "January 21, 2016"
output: html_document
---
Can you take a look?

**Comment by daattali** [comment]
I assume you're referring to an interactive Rmarkdown document?  Interactive Rmarkdown documents have to be hosted on a shiny server. Jekyll is not a shiny server, it will not work.  Jekyll can only host plain HTML files

**Comment by abiyug** [comment]
Hi Dean,
Lets take the DataTable (DT) for example. I can save the HTML source and open it on a PC that doesn't have shiny server. The browser is supposed to render it without any shiny server. Isn't that how Jekyll should work also?

Thanks,

Abiyu

**Comment by daattali** [comment]
When you save it, does it only produce the HTML file, or are there other
files that are created too?  If it's literally just an HTML file, then yes
jekyll should be able to render it correctly.  To test it out, attach the
HTML file here and I'll try to open it. If I can render it properly then
jekyll should too, if not then that's the problem

---
http://deanattali.com

**Comment by abiyug** [comment]
Attached is the file.

Here is the markdown code:

---
title: "Data Table"
author: "Abiyu Giday"
date: "January 21, 2016"
output: html_document
---
###Test DT

This is the table.

```{r sdata,results="asis",  message=FALSE }
library(dplyr)
library(car)
library(knitr)
library(DT)
datatable(cars)
```

*'Abiyu Giday | Principal Consultant*

*Antex Ultimate Solutions | www.antexusolutions.com
<http://www.antexusolutions.com/>(O) 703-436-4118** | (C)  703-459-0943
(e) matt.giday@antexu <http://goog_1484985646/>solutions.com
<http://solutions.com/>*



This message may contain information which is confidential and subject to
legal privilege. If you are not the intended recipient, you may not peruse,
use, disseminate, distribute or copy this message. If you have received
this message in error, please notify the sender immediately by email,
facsimile or telephone and return and/or destroy the original message. The
views and/or opinions expressed within the contents of his message are not
necessarily those of Antex Ultimate Solutions Group or their affiliates and
subsidiaries.

**Comment by daattali** [comment]
Ok I took your code (I replaced `cars` with `mtcars` because I don't want to download a new package), and I uploaded the HTML to my website.  [Here is the HTML file](https://github.com/daattali/daattali.github.io/blob/master/test.html) that RStudio created, and [here](http://deanattali.com/test.html) is how it shows up on my site.  Looks fine.  Note that the file has to be `.html`, not `.md`.

**Comment by daattali** [comment]
You can copy the exact file ([this one](https://github.com/daattali/daattali.github.io/blob/master/test.html)) to your website. There's no reason it wouldn't render.  I'm assuming you're using GitHub Pages, if you're using jekyll locally then maybe there's something else that's breaking it, I don't know anything about local jekyll.

**Comment by abiyug** [comment]
I agree with you! There shouldn't be any reason. I will try again and revert back to you.

**Comment by abiyug** [comment]
Have you tested it inside the beautiful Jekyll?

**Comment by daattali** [comment]
my website is a fork of beautiful jekyll. There really should not be any issue if it's just an HTML file with no other dependencies and our file is named correctly. Again, this is only assuming you're in GitHub Pages. If you are using github pages then you can just link me to the file on github that's not showing up properly if you

**Comment by abiyug** [comment]
It isn't rending the table for me. Take a look.

http://abiyug.github.io/2016-01-21-DT-Test/

*'Abiyu Giday | Principal Consultant*

*Antex Ultimate Solutions | www.antexusolutions.com
<http://www.antexusolutions.com/>(O) 703-436-4118** | (C)  703-459-0943
(e) matt.giday@antexu <http://goog_1484985646/>solutions.com
<http://solutions.com/>*



This message may contain information which is confidential and subject to
legal privilege. If you are not the intended recipient, you may not peruse,
use, disseminate, distribute or copy this message. If you have received
this message in error, please notify the sender immediately by email,
facsimile or telephone and return and/or destroy the original message. The
views and/or opinions expressed within the contents of his message are not
necessarily those of Antex Ultimate Solutions Group or their affiliates and
subsidiaries.

**Comment by daattali** [comment]
Ah, I see. It's because it's trying to render as a post (inside the _posts folder). But anything inside the _posts folder gets rendered in a special way , it's not going to be pure HTML, it's going through some layers of abstraction. I'm guessing that the HTML gets escaped at some point.  To include a pure HTML page, it needs to be its own independent file, that doesn't go through the jekyll markdown --> html conversion (which does happen for blog posts). So if you'll move the file to the root directory, it should work.  If you want to keep it as a post, then.... I'm not sure. I suppose  Google is your friend, but that's not something I ever tried.

**Comment by abiyug** [comment]
But, it renders fine outside of beautiful Jekyll ...,

**Comment by daattali** [comment]
Then you can try to have a look at how a "post" is rendered by looking at [the post layout](https://github.com/daattali/beautiful-jekyll/blob/master/_layouts/post.html) and the [default layout](https://github.com/daattali/beautiful-jekyll/blob/master/_layouts/default.html) which it build on.  You can play around with those layouts to see where the problem is. It might not be very fun to do

**Comment by abiyug** [comment]
Actually I have HTML embedded in the post that is working already. So not sure it will render one HTML but not the other.

http://abiyug.github.io/2016-01-19-Salary-Comp-dplyr-ggplot/

At any rate, I think this is very important feature to have. But understand beautiful Jekyll doesn't support it.

**Comment by abiyug** [comment]
Will give it a try, thanks.

**Comment by daattali** [comment]
Ah! I found the problem. I did what I told you - started from a fresh template and slowly added things in. It was not fun, as I said :)  Looks like the problem is that I'm including jquery JavaScript, and the HTML that rstudio creates also laods jquery. Loading jquery twice on the same page is known to cause huge problems.  I'm not 100% how I'll fix that for now, but at least I can tell you that's the problem. So for you right now if you want a quick fix, just remove the line that includes jquery ([this line](https://github.com/daattali/beautiful-jekyll/blob/3ae5f561acc2e877462a93ecc540e7c921fbdeca/_layouts/default.html#L11)

**Comment by daattali** [comment]
Sorry, actually, don't do that! Removing jquery will fix that specific page but it will break all other pages (because other pages do require it). Let me think about it some more. But at least now it's not a mystery!

**Comment by daattali** [comment]
Hey @abiyug I think I fixed the issue. Can you fork beautiful jekyll now and try it again?

**Comment by abiyug** [comment]
I will test and revert back to you!

*'Abiyu Giday | Principal Consultant*

*Antex Ultimate Solutions | www.antexusolutions.com
<http://www.antexusolutions.com/>(O) 703-436-4118** | (C)  703-459-0943
(e) matt.giday@antexu <http://goog_1484985646/>solutions.com
<http://solutions.com/>*



This message may contain information which is confidential and subject to
legal privilege. If you are not the intended recipient, you may not peruse,
use, disseminate, distribute or copy this message. If you have received
this message in error, please notify the sender immediately by email,
facsimile or telephone and return and/or destroy the original message. The
views and/or opinions expressed within the contents of his message are not
necessarily those of Antex Ultimate Solutions Group or their affiliates and
subsidiaries.

**Comment by abiyug** [comment]
Tested and it renders the HTML widgets fine now!  Updated the
footer-scripts.html
script with your changes in the "_includes" folder.

FYI - best visual on Chrome - compare to Safari and Firefox.

Thanks again

**Comment by abiyug** [comment]
One more question - why doesn't I am able to post .html.  But, r code in
the r-markdown doesn't seem to render example after saving xyz.md file that
contains this code

```{r, echo=FALSE}
plot(cars)
```
doesn't plot the graph on beutiful jykell.. it just shows the code only.

*'Abiyu Giday | Principal Consultant*

*Antex Ultimate Solutions | www.antexusolutions.com
<http://www.antexusolutions.com/>(O) 703-436-4118** | (C)  703-459-0943
(e) matt.giday@antexu <http://goog_1484985646/>solutions.com
<http://solutions.com/>*



This message may contain information which is confidential and subject to
legal privilege. If you are not the intended recipient, you may not peruse,
use, disseminate, distribute or copy this message. If you have received
this message in error, please notify the sender immediately by email,
facsimile or telephone and return and/or destroy the original message. The
views and/or opinions expressed within the contents of his message are not
necessarily those of Antex Ultimate Solutions Group or their affiliates and
subsidiaries.

**Comment by daattali** [comment]
@abiyug it's better if you don't change the file yourself as I said. Just fork this repository, there are a few more changes that fixed the problem.

Your second question: I don't understand what you mean. You're saying only code shows up but the graphs don't?  The previous example of the cars table shows that you CAN post results of R, as long as you're uploading the html.
