### ISSUE TITLE
Deploy with Docker

### ISSUE THREAD

**Issue by adrianocanofre** [daattali/beautiful-jekyll#302]
I'm fork this repository and start the beautiful-jekyll with docker, but this error happens:

```
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    Invalid US-ASCII character "\xE2" on line 5
```

**Comment by daattali** [comment]
Sorry I'm not able to support/solve anything related to docker. I
personally haven't tried using docker with this theme. You can look through
the history of the code commits to see who added the docker code and try
tagging them.

On Jan 14, 2018 09:33, "Adriano Canofre" <notifications@github.com> wrote:

I'm fork this repository and start the beautiful-jekyll with docker, but
this error happens:

Conversion error: Jekyll::Converters::Scss encountered an error while
converting 'assets/css/style.scss':
                    Invalid US-ASCII character "\xE2" on line 5

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/daattali/beautiful-jekyll/issues/302>, or mute the
thread

**Comment by adrianocanofre** [comment]
Ok, I ran the docker code described in readme, because I'm trying run local server
```
docker run -p 4000:4000 -v `pwd`:/app mangar/jekyll:1.1 bash -c "bundle install; bundle exec jekyll serve"
```

**Comment by daattali** [comment]
@jennydaman that is a **much** nicer version of a dockerfile. @adrianocanofre can you confirm if this suggested setup works for you too?

**Comment by adrianocanofre** [comment]
Thank you @jennydaman , the Dockerfile run perfect. @daattali, yes, I build and run the docker and I was able to run a local server.

**Comment by jennydaman** [comment]
@daattali Do you want a PR for this

**Comment by daattali** [comment]
@jennydaman yes, please. And update the corresponding section in the README at the same time.

Would deleting the gemfile.lock be required even if it gets cleaned up?

**Comment by jennydaman** [comment]
`bundle install` is going to regenerate a cleaner Gemfile.lock. If `Gemfile.lock` is not deleted, then some extraneous lines will remain. It's not too much of an issue besides that it annoys me. What do you prefer?

**Comment by daattali** [comment]
If you think there are remnants of a mingw run in that file, then it should be cleaned up.

**Comment by daattali** [comment]
this was fixed by @jennydaman
