### ISSUE TITLE
Cookie Consent

### ISSUE THREAD

**Issue by ShahnurIslam** [daattali/beautiful-jekyll#313]
Hey Dean,

Love Beautiful Jekyll and it's helped a lot of with my blogging. I live in the UK and under new EU regulations we need to add cookie consent for cookie tracking on the site. Would you be able to add this feature or tell me how I can do it?

Thanks,
Shan

**Comment by daattali** [comment]
This theme does not use cookies to track any information. The only tracking
I can think of is if you manually add something like Google Analytics.

On Jan 22, 2018 7:27 PM, "Shahnur Islam" <notifications@github.com> wrote:

Hey Dean,

Love Beautiful Jekyll and it's helped a lot of with my blogging. I live in
the UK and under new EU regulations we need to add cookie consent for
cookie tracking on the site. Would you be able to add this feature or tell
me how I can do it?

Thanks,
Shan

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/daattali/beautiful-jekyll/issues/313>, or mute the
thread

**Comment by OCram85** [comment]
I found this recently: https://cookieconsent.insites.com/. Maybe it helps in any way ^^

**Comment by daattali** [comment]
I'm so glad this cookie law hasn't reached North America...

**Comment by OCram85** [comment]
@ShahnurIslam . Jus now I read, the EU regulations needs to be adopted by every Country itself. So if I get it right, each EU country needs to introduce the regulation in it´s own `law`s. So Germany didn't introduce this regulations. May the UK didn't introduce this as well? - In this cases your don't need to respect the EU cookie law?!?!

**Comment by daattali** [comment]
I want to repeat though: this theme, by default, does not use cookies, so this should not be an issue anyway

**Comment by ShahnurIslam** [comment]
Hey Dean thanks for replying.
I know by default it doesn't but I do use the Google Analytics tracking which I do need to get consent for. I managed to get a snippet of code that just needs to be added to the header of the site. Any advice?

**Comment by OCram85** [comment]
# Put the code in a new html file in the `_includes` dir
# Include the file in the desired header position with {%- include <filename>.html -%}

**Comment by daattali** [comment]
You can look at @OCram85 's latest commit to see this in action: https://github.com/daattali/beautiful-jekyll/commit/7677fbd01a9cdd0173c7a41b9551674c65e7ac4d

Notice that he added a file `includes/matomo.html` with the HTML he wanted to insert, and made a small addition to `_includes/header.html` where he added the line `{% include matomo.html %}` in order to inject that html.

**Comment by ShahnurIslam** [comment]
Thanks all, I managed to do it in the end by adding it to the includes/head.html file at the bottom.

**Comment by daattali** [comment]
Feel free to submit a pull request, and make it a configurable setting,
like what Marco did in the link I sent earlier

**Comment by ShahnurIslam** [comment]
Ok will give it a go. Thank Dean!




________________________________

**Comment by OCram85** [comment]
@ShahnurIslam: :question:  I decided to implement https://cookieconsent.insites.com/ on my instance of beautiful-jekyll. First I thought I could share it with the jekyll community via gem but this would exclude all gh-pages users. So If you still looking for a solution on your instance you can look at my recent PR: https://github.com/OCram85/OCram85.github.io/pull/10
