### ISSUE TITLE
upgrade front awesome version 5 

### ISSUE THREAD

**Issue by allan9595** [daattali/beautiful-jekyll#324]
Hello, i try to add discord font awesome on my site but seems like Beautiful jekyll still use font awesome version 4 so my discord icon not works. Could you update it to version 5 for font awesome?

**Comment by daattali** [comment]
Sure I can look into that when I have a few minutes. I would also accept a
pull request

**Comment by allan9595** [comment]
Thank you !

**Comment by daattali** [comment]
Looks like this will have to wait a bit. fontawesome just released version 5.0.6 17 days ago, and it looks like the CDNs serving fontawesome haven't updated yet (which I totally understand if it's only been 17 days). I checked https://www.bootstrapcdn.com/fontawesome/ and https://cdnjs.com/libraries/font-awesome both of them are still serving 4.x

I'll check again periodically and update when it's available. In the meantime feel free to change it locally on your project to the new version by actually downloading the fontawesome files and referring to the local copy rather than to an online copy

**Comment by shyd** [comment]
I have done this in my fork in order to use the docker icon 🐳  But I use gulp task runner with bower to build my site. <https://schuett.io>
I will create a PR with the icon changes later. Then you can merge it if v5 becomes available at CDNs.

Cheers

**Comment by OCram85** [comment]
@shyd: Awesome Blog! Super Arbeit :+1:

**Comment by allan9595** [comment]
@shyd Do you still able to use the rss feed after you updated to the font awesome 5? My site runs into a rss feed issue now. (https://untcybersecurity.com/feed.xml)

**Comment by shyd** [comment]
@allan9595 Yes, it's stable for me. I just branched my feature branch into gh-pages for demonstration: <https://shyd.github.io/beautiful-jekyll/feed.xml>

**Comment by andreas-paul** [comment]
Is there any update on the migration to Font Awesome v5? I tried to implement it myself but I can't get the icons of v5 to work. Seems like the cdn's are still on v4 which is quite strange.

**Comment by daattali** [comment]
Not going to be implemented until I have a good reason to

**Comment by daattali** [comment]
You can look at [this PR](https://github.com/daattali/beautiful-jekyll/pull/400) by @shyd if you want to upgrade!

**Comment by daattali** [comment]
Done
