### ISSUE TITLE
Is remote_theme supported?

### ISSUE THREAD

**Issue by chfast** [daattali/beautiful-jekyll#339]
I tried to use

```
remote_theme: "daattali/beautiful-jekyll"
```

in my GitHub Pages config. This does not seem to produce good results (https://chfast.github.io/How-to-explicit-NOT-initialize-variables-in-cpp/). 

Should that work?

**Comment by daattali** [comment]
This is a fairly new feature of github (allowing custom themes to use `remote_theme`), and I haven't yet found the time to make beautiful-jekyll compatible with that. So it does not work yet.

If someone wants to help making the necessary changes, I would appreciate the help!

**Comment by dkoprowski** [comment]
Hi @daattali - some news on that :) ?

**Comment by daattali** [comment]
Sorry @dkoprowski I still haven't looked! If you're familiar with it, I would not oppose to a pull request if you'd like to help :)

**Comment by dkoprowski** [comment]
Unfortunately I'm not familiar with Ruby and Gems ;)

**Comment by abelcheung** [comment]
Some great (and bad) news: I have managed to using it as `remote_theme` in Github Page (running in [one of my pet project](https://abelcheung.github.io/rifiuti2/) right now, thanks for the great work!), though quite a lot of files have to be cloned manually in order to get it to work.

With my (limited) understand of the `remote_theme` feature, the following 4 folders can be utilized without copying:
* `_layouts`
* `_includes`
* `_sass` (probably can be ignored since this theme is not using sass)
* `assets`

So the major obstacle probably involves moving css, javascript, images and all sort of include files to their proper place, and update links / references to them. I'm still new to Jekyll and even Ruby in general, so perhaps somebody more experienced can correct me if anything is missing. :)

**Comment by abelcheung** [comment]
For those interested, one can check out [my example repo](https://github.com/abelcheung/site-test/) which is using a restructured beautiful-jekyll as remote theme. At a minimum, only a few config files and top level pages need to be copied in order to establish a working site. In particular, notice addition of `plugin` entries and `remote_theme` setting in `_config.yml`.

On second thought, I doubt this feature goes against daattali's interest, since the essence of `remote_theme` is to avoid forking and only copy files necessary for overriding defaults, thus not included into fork count (as an easily monitored user count of this theme). Unless daattali gives the green light and users do really want the feature, perhaps pull request won't be submitted.

**Comment by daattali** [comment]
@abelcheung I would be happy for a PR to support this! The `remote_theme` option seems to be much cleaner and easier for end users, which is my ultimate goal. I don't care about the numbers as much.

**Comment by daattali** [comment]
`remote_theme` is now supported
