### ISSUE TITLE
bigimg not rendering

### ISSUE THREAD

**Issue by eickhoff** [daattali/beautiful-jekyll#340]
Hi,

I am trying to use a bigimg in the header of my blog posts. After some back-and-forth with relative and absolute hyperlinks, everything looks fine now on the code side, the links in **header-big-imgs** are all correct and work, but somehow the **big-img intro-header** element is not assigned a style element setting the background image.

If you have any suggestions as to why this could happen, I'd be happy for pointers.

**Comment by daattali** [comment]
I suggest forking a fresh copy (into a different project if you don't want to mess with your current one) and seeing that bigimg works on the sample posts. Form there add things slowly and see when it breaks. The feature itself works so I don't know what in your settings broke it.

I'm closing this issue since this isn't a bug or a feature request. For help, I recommend going to a Jekyll support forum. Thanks!
