### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by npes87184** [daattali/beautiful-jekyll#349]
nokogiri has known vulnerability found in version 1.8.1.

**Comment by daattali** [comment]
Yes I saw the massage, thank you! This is only in the ruby gem, and this theme is officially only supporting the use of github pages. If you use ruby for deployment, as i mention in the README, I don't provide much info or support with that. I myself don't use ruby so if anyone uses this theme in ruby rather than github they'd be responsible for everything that is involved

**Comment by daattali** [comment]
fixed by @OCram85
