### ISSUE TITLE
[Umbrella Task] Verify beautiful-jekyll is GDPR compliant

### ISSUE THREAD

**Issue by OCram85** [daattali/beautiful-jekyll#356]
# Meta
### :question:  About *[Umbrella Tasks]*
> [Umbrealla Tasks] are logical constructs to manage complex issues broken down in multiple small tasks. This should help with getting an overview, plan and delegate complex tasks. 

## :arrow_up_small: Blocks _(Parent Tasks)_

# :package: Content

This would be awesome for EU based users 👍 

> I'm starting to work on this in the next days :D ... 25. Mai is coming 😸 

### Google Font Usage
To avoid privacy policy section it maybe would be better not to use the google CDN.
 One possible way would be using something like [this](https://google-webfonts-helper.herokuapp.com/fonts)

- [ ] #358 

### jQuery
Using it from local and not loading it from CDN

- [ ] #357 

### FontAwesome
Using FontAwesome from local store to prevent privacy policy definition caused by third party cookie
- [x] #359 

### Bootsrap
- [x] already local and updated
### Cookies
How to deal with opt-out? Maybe implementation of [CookieConsent](cookieconsent)

### Privacy Policy
beautiful-jekyll could provide a simple template page explaing the internal used resources

### Social Share / Github buttons
If the clients IP address will be transferred this needs to be addressed.

### Disqus
Usage needs a privacy policy section as well

> Any more ideas or recommendation?

**Comment by OCram85** [comment]
@daattali: What do you think about external resources like jQuery, GoogleFonts... Do you want them as external or could it be possible to implement them into the beautiful-jekyll itself?
It should be no difference for end users. But it would simplify the privacy policy creation. It's your design decision :smiley_cat:

**Comment by OCram85** [comment]
#### FYI:
- I've contacted the github team and asked for any advice relating the GDPR and GitHub Pages based blogs.
- In addition to that I started a conversation in the community section. [How to deal with GDPR...](https://github.community/t5/Pages/How-to-deal-with-GDPR-on-github-pages-based-blogs/m-p/7719#M637)

**Comment by daattali** [comment]
Thanks for the initiative and eagerness to move this forward fast! To be honest I don't know if simple static blog sites like the ones served with this template need to worry about GDPR to such a high degree.

As of right now I would prefer to stay away from all of this. But I want to keep the issue open and let others chime in because I'm not very informed about these laws and how others in similar situations handle them. I'm interested to know if/how other jekyll templates changed because of GDPR. If you get any more info from github, from your discussion thread, or from other places, please do update me. I I really appreciate your contribution here

To answer to each of your points separately:

- Beautiful jekyll and its websites do not collect or store any information (so I don't think a privacy policy is needed)
- Disqus does have its own popup that automatically gets injected, so no need to worry about that.
- Matomo already has an opt out link
- We could add CookieConsent although I think many people who use beautifuljekyll don't actually use any cookies, so again it might be too much (the only cookies used may be from google analytics? Or can you think of other cookies?).
- Google Analytics is the only thing that is completely uncovered, but again that's only used by a small fraction of people, and I would imagine Google should be responsible for having a popup for that, just like Disqus does, but I might be very wrong.
- Social share buttons - we're not collecting or storing any info, before actually sharing any content, the third party website asks for permission explicitly, I think that's enough
- Removing CDNs also feels a bit much for me :)

**Comment by daattali** [comment]
I tried googling a little bit about jekyll+gdpr and didn't find too much, but I did see that someone brought up a similar issue on the MinimalMistakes theme, and the author there also had reservations because of the added complexity, and he's also wondering how others are handling it. Would be interesting to see how that issue, and other popular jekyll themese, evolve https://github.com/mmistakes/minimal-mistakes/issues/1662

**Comment by johnmackintosh** [comment]
I found this article which suggests that Google Tag manager is key to managing the likes of Disqus and other 3rd party plug ins :

https://brianclifton.com/blog/2018/04/16/google-analytics-gdpr-and-consent/

I found it quite straightforward to get  a cookie consent warning (one with opt in /opt out) to appear.
What I don't know is if the javascript callback hook (whatever THAT is) is actually doing what it's supposed to.
When I add that code in, I don't get a warning. Without the code, I get the consent warning but presumably no action is taken despite what the user selects

**Comment by OCram85** [comment]
@daattali: I just tried to sensibilize about the usage of beatiful-jekyll and the GDPR.

## About external resources

You're right, beautiful-jekyll doesn't collect any data or uses own cookies. And all of the the used external resources have their own privacy policy. But since we are using these, the browsers IP will be transparent to these CDNs. So I'm forced either to write an complex privacy policy which explains this. That's why I tried to remove the external sources.

## Cookies
The fact some of used services like Disqus, FontAwesome... uses cookies the GDPR requires to give the users a possibility to deny them. That's  why many started using services like *Cookie Consent.* Now the implementation totally depends on the individual country laws. Some need just the opt-in feature, some need a opt-out. But I'm not quite sure how to opt-out such third party cookies.

## GDPR in general
On top of that it totally depends on whether the individual implementation is for private or business projects. So I didn't want to panic someone ^^

**Comment by OCram85** [comment]
@johnmackintosh: I'm dealing with the same javascript problems and cookie consent. It totally depends on the used beautiful-jekyll features. Is it possible to use the liquid markups in a java-script? Maybe this would help creating dynamic scripts for opt-out (like the [matomo cookie](https://developer.matomo.org/guides/tracking-javascript-guide#step-2-asking-for-consent-through-your-privacy-notice) )

**Comment by johnmackintosh** [comment]
@Ocram85 : I honestly don't know anywhere near enough about JavaScript to answer that, sorry. 
 

I have the consent pop-up working, and I also added a privacy page detailing exactly what information _may_ be captured.
I opted to make Google Analytics less precise, and disabled social media sharing options.
I'm not sure what else to do with this?

**Comment by OCram85** [comment]
@johnmackintosh : thanks for your feedback

I've also added the consent pop-up and privacy page. In addition I had to host the domain by my self.

But I'm not quite sure if we have to implement a opt-in for the cookies or something similar.

**Comment by daattali** [comment]
Closing as I don't think a simple static blogging website should invest so many resources into GDPR
