### ISSUE TITLE
navbar menu on both sides of logo?

### ISSUE THREAD

**Issue by CarlosGrohmann** [daattali/beautiful-jekyll#386]
Is it possible to have menu items (navbar) on both sides of the site logo? Currently the menu items are on the right side, and if you create too many of them, they will appear behind the logo. (of course, this varies with window size, but the idea would be for the menu to look good even with smaller windows)

**Comment by daattali** [comment]
No that's not possible. Since this is a generic theme used by thousands of people, some design decision had to be made and unfortunately nothing is a perfect one-size-fits-all for everybody. Using the template as-is won't achieve that, but since it is open source you're free to change the code however you'd like to do that.
