### ISSUE TITLE
Google analytics tracking code should be in head tag instead of end of body

### ISSUE THREAD

**Issue by agroconscious** [daattali/beautiful-jekyll#406]
Tag Assistant  returns a `Code found outside of <head> tag ` when i test my site.

When i click on more information, it says; 

```
 **Move the tag inside the head.**
We have detected that the Google Analytics tracking code is outside of the
section on this page. This decreases the likelihood that the tracking beacon will be sent
before the user leaves the page.
One of the main advantages of the asynchronous snippet is that you can position it 
at the top of the HTML document. This increases the likelihood that the tracking beacon
will be sent before the user leaves the page. We've determined that on most pages, 
the optimal location for the asynchronous snippet is at the bottom of the section, 
just before the closing tag.
Solution: Ensure that you add the Google Analytics tracking code onto this page before the closing tag.
```

How do i fix this?
thanks, my first attempt with jekyll

**Comment by daattali** [comment]
Thanks for bringing this up. Historically, there was a debate about where the google analytics code should go, and it used to be a better idea to place it at the end of the page. Now it's recommended to have it at the top, inside the head tag, so that it can also track pages that haven't finished loading. That's what the recommendation is saying. The fix is by moving the google analytics code that is currently being loaded from the _includes/footer-scripts.html file into the head tag. This can be a good idea to implement for beautiful jekyll.

**Comment by daattali** [comment]
Solved
