### ISSUE TITLE
Website not mobile-friendly

### ISSUE THREAD

**Issue by dewrs** [daattali/beautiful-jekyll#425]
Good day, 
Firstly I would like to thank you very much for offering such a beautiful and easy to understand Theme/Tool. 
I am not a computer expert, but managed to make my own website. Unfortunately I cannot figure out how to adjust the settings to allow my site to show properly on mobile devices. It currently will not center and looks off in general. Which parameters will have to be adjusted to reach my desired viewability?
Website: siegener-wirtschaftsjuristen.de or dewrs.github.io
Github: github.com/dewrs

Any help will be greatly appreciated

**Comment by JackGruber** [comment]
Hi,

i think your problem is the word "Wirtschaftsjuristen" 
![grafik](https://user-images.githubusercontent.com/24863925/48438797-11cb4180-e785-11e8-95ee-7b7419ccdd0c.png)

You can reduce the  `.intro-header .page-heading h1` font-size for ` @media only screen and (min-width: 768px) `
https://github.com/dewrs/dewrs.github.io/blob/master/css/main.css#L538

**Comment by dewrs** [comment]
Thank you for your quick response. I changed the amount of pixels used in line 538 as you described. This improved the desktop version, but unfortunately no changes to the phone viewability. Due to your suggestion I am also confident that changing the length of the title will solve my problem.

**Comment by daattali** [comment]
@dewrs I agree that having a very long word is going to be problematic on narrow devices, such as phones. This is not a limitation of this theme specifically, it is a problem that every website has to deal with.

@JackGruber thanks for helping
