### ISSUE TITLE
YAML front matter parameters "bigimg" and "comments" not working

### ISSUE THREAD

**Issue by abiyug** [daattali/beautiful-jekyll#453]
Thank you for submitting an issue!

Please only submit bug reports or feature suggestions. Please do not submit support requests and general help questions in this forum.

I have added the **bigimg** parameter as described here https://github.com/daattali/beautiful-jekyll, and added the images and relevant path, but the images do not render on the front page. Here is what I have in the YAML front matter: 

```
bigimg:   
- "/img/big-imgs/img_one.jpg" : "One"   
- "/img/big-imgs/img_two.png"  : "Two"   
- "/img/big-imgs/img_three.png" : "Three"  
```

Also enabled Disqus, and was supposed to be able disable per page  **comments** by adding "comments: false" for each page front YAML.  I tried  to disable for the index.html page by adding the following in the front  YAML, but th Disqus comment on the index page is still showing! Here is  what I have in the YAML front matter: 

comments: false

**Comment by abiyug** [comment]
Thanks for taking time to respond Dean! One of the early adapters o jekyll, I forked the version about 3  years ago., Just went over the YAML front matter on the README, and it  does NOT include `"bigimg" `parameter.  Given that, what is the best route forward if I want `bigimg` feature enabled?

**Comment by daattali** [comment]
Unfortunately that's one issue that doesn't have a good solution (keeping a
fork up to date with the original). You can try to look at my code or my
commit history and copy the relevant bits of code to your repo. Or it might
be easier to just save for current config file, posts, and whatever other
content you have, then re-fork mine and then add all your content. There's
been a lot of features over the last 3 years, and this shouldn't be tooo
difficult, certainly easier than my first suggestion.

**Comment by abiyug** [comment]
Ok! Thanks for your suggestion!

**Comment by thestumbler** [comment]
For completely different reasons, I just finished updating my version of you theme.  I can attest, it wasn't very difficult for me (and I hadn't updated since early 2016).  In fact, I thought I had read on a forum post somewhere that you had abandoned Beautiful Jekyll, so in the back of my mind, I was worried about how hard it was going to be to change themes.  I had made some very minor tweaks to the theme, and just recently made a custom CSS file for two pages.

I was happy to see that the theme is being updated, and also that it was pretty easy to update my blog.  The _config.yml file was quite straightforward to update. I had rearranged my file structure to include collections, but this was also simple to fix. I also discovered that I hadn't needed to dink with your main.css file, as there is a mechanism to include you own page-specific css file.  That worked great.

The biggest problem for me was that you changed the name of the page-specific avatar image from "avatar" to "image".  I had to run "sed" on my files which had their own avatar, but that was pretty painless all things considering.

**Comment by daattali** [comment]
I'm glad to hear it wasn't too bad. I wonder where you read that the theme was abandoned? The frequency of updates has significantly slowed down but that's in large part thanks to the fact that it's been around long enough that it's stable by now and most major features I wanted to implement have been done

**Comment by thestumbler** [comment]
> I wonder where you read that the theme was abandoned?

I wondered that, too, and poked around, and found [this post](https://github.com/daattali/beautiful-jekyll/issues/237#issuecomment-327560646).  I didn't understand at the time that you were only talking about the gem, not the whole theme.

Thanks for your continued efforts maintaining this theme.  I think I've now structured my files and directories so that future updates will be pretty simple to incorporate.
