### ISSUE TITLE
Staticman GitHub App support

### ISSUE THREAD

**Issue by wini3d** [daattali/beautiful-jekyll#541]
More on a feature request. I was wondering if you are planning to have this supported or if it is already, is there a doc?

https://github.com/apps/staticman-net

Also, any guide on how to setup your own heroku staticmanlab instance?

**Comment by daattali** [comment]
Static man is already supported for comments. What feature exactly are you requesting? I try not to bloat this theme with too much info specific to one small feature in it (that is - I prefer not to have huge docs sections dedicated to staticman)

**Comment by wini3d** [comment]
Yes, using the[ staticman github app](https://github.com/apps/staticman-net) instead of the `staticmanlab` collaborator which I read has lesser limits.

**Comment by daattali** [comment]
I'll defer to @VincentTam - he brought in staticman and would understand the question better

**Comment by VincentTam** [comment]
> Yes, using the staticman github app v3 instead of the @staticmanlab collaborator v2 which I read has lesser quota.

@wini3d Since I ported Staticman Integration from Minimal Mistakes in #440, **this theme has been using Staticman v3 API scheme**, which has been merged in eduardoboucas/staticman#219.  After several months, the action URL was moved into JS in #521 to avoid spam bots.

https://github.com/daattali/beautiful-jekyll/blob/c74b5030c67eae26d6e443f71db4294d5ba54e74/js/staticman.js#L14

Since I've (and I'll) *never* used GitHub Apps (for reasons listed in my earlier comment https://github.com/eduardoboucas/staticman/issues/299#issuecomment-508029359.), I'll leave interested users to write the instructions for using GitHub Apps.  Be aware that

1. One can use this theme for either the new GitHub Apps or the legacy authentication method.  (See the explanations in the following paragraph.)
2. The **official** production and development **API instances aren't always stable**, as reported in eduardoboucas/staticman#307.

Whether the app version is used or not, the v3 API scheme and the input and output data format has not been changed.  As a static blog theme, it doesn't care the actual functioning of the API server—that's a Staticman (as a node.js app) issue.  Instead, we handle data files received from the API server, and render them into HTML elements to be displayed.  Staticman's support for GitHub Apps eduardoboucas/staticman#255 has *not* changed the input/output data structure nor the POST URL structure introduced in eduardoboucas/staticman#219, based on which #440 was made.  Therefore, I see ***no* need to modify our Jekyll-HTML template** in view of eduardoboucas/staticman#255.

My bot @staticmanlab, forked from the `dev` branch after eduardoboucas/staticman#219 was merged, supports both v2 and v3.  That's in line of the app's author's original intention in https://github.com/eduardoboucas/staticman/issues/243#issuecomment-453876235.

> Also, any guide on how to setup your own heroku staticmanlab instance?

That's off-topic here, for the reason I've explained above.  You may go to the official Staticman repo to start an issue there—you've done that in eduardoboucas/staticman#310, or leave a comment under my blog article [*Staticman API Hosting 2018*](https://vincenttam.gitlab.io/post/2018-09-16-staticman-powered-gitlab-pages/2/).

* * *
:warning:  Remarks:

:no_entry_sign: **Staticman v2 no longer works** on official production instance, as reported in https://github.com/eduardoboucas/staticman/issues/306.

**Comment by wini3d** [comment]
> My bot @staticmanlab, forked from the dev branch after eduardoboucas/staticman#219 was merged, supports both v2 and v3. That's in line of the app's author's original intention in eduardoboucas/staticman#243 (comment).

Thank you. So are you suggesting to fork the merge from eduardoboucas/staticman#219 to have the same exact copy that your staticmanlab herokuapp is using?

**Comment by VincentTam** [comment]
In [my linked guide for setting up Staticman API](https://vincenttam.gitlab.io/post/2018-09-16-staticman-powered-gitlab-pages/2/), there's a comparison between my `deploy` branch and the `dev` branch: https://github.com/eduardoboucas/staticman/compare/dev...VincentTam:deploy.  I'll update that because I meant the `dev` branch by the moment of writing the post: https://github.com/eduardoboucas/staticman/compare/55d14306d851059a2a27d24b5eb4cb17c5009477...VincentTam:deploy.  This comparison summarises my customization of Staticman's code last year.

The great thing about a Git branch is that it gives a short reference name to a feature/modification, so that you can easily make comparisons.  You don't need to follow every step in my post, like

    echo "web: npm start" > Procfile

Braching against the `deploy` branch will do.  You might try eduardoboucas/staticman#301 if you want.

**Comment by wini3d** [comment]
Thanks @VincentTam . I just tried your deploy branch, the invite went successfully but getting 500 Internal Server Error when posting comments. I just changed the form action url from your staticman3 to my heroku url.

https://github.com/eduardoboucas/staticman/issues/311

**Comment by daattali** [comment]
I'm going to close this issue because it's not relevant to beautifuljekyll - feel free to continue this discussion privately or in another repository where it makes sense :)

**Comment by VincentTam** [comment]
> Thank you. So are you suggesting to fork the merge from [eduardoboucas/staticman#219](https://github.com/eduardoboucas/staticman/pull/219) to have the same exact copy that your staticmanlab herokuapp is using?

@wini3d I had lost my concentration for a few seconds browsing various issues.  I should have answered your question in a GitHub issue under Statimcan's repo since that's a question about Staticman's API rather than this theme's Staticman integration.

To understand what type of questions about Staticman is on-topic here, you may think about an ATM.  Staticman's API is like the ATM's interface.  A static blog theme deals with stuff "in front of" the interface (e.g. conversion of HTML form data into an appropriate POST request), and it doesn't care about what's "behind the ATM's interface" (e.g. how the POST request is converted to a Git commit object).

**Comment by wini3d** [comment]
Thanks, I understand that and I have updated some findings [here](https://github.com/eduardoboucas/staticman/issues/311). We can move this discussion now to that issue.

**Comment by VincentTam** [comment]
> I'm going to close this issue because it's not relevant to beautifuljekyll - feel free to continue this discussion privately or in another repository where it makes sense :)

@daattali **Documentation request/questions for setting up** a site using this theme with an existing **Staticman v3** API is on-topic here, since there's some theme-specific parameters in each theme with Staticman support.  Here's the right place to place to ask questions/discussions about these parameters.

https://github.com/daattali/beautiful-jekyll/blob/96c25086b57e6af1fd44eec8f0bcdadce33730a7/_config.yml#L130-L138

I interpret the question on the top in this way: "Does the above parameters support the GitHub Apps version of Staticman?  Does this repo's README cover this?".  That's surely on-topic here.  Since this repo's README doesn't cover the GitHub Apps version of Staticman, a normal user of this theme might be in doubt of this theme's capability to support that.  As a result, it would be good to see some volunteer updating the README regarding the the GitHub Apps version of Staticman.  I've never used that, so I have to leave that to others.

> More on a feature request. I was wondering if you are planning to have this supported or if it is already, is there a doc?
>
> https://github.com/apps/staticman-net

**Comment by daattali** [comment]
@VincentTam do you know if there are any updates on staticman? I just checked https://staticman.net/ and there is no mention at all of a v3 API, only v2. If v3 isn't official or recommended yet, I'd like to close this issue

**Comment by daattali** [comment]
As far as I understand, v3 that was discussed here is not an official recommendation. Due to lack of response here, I'm closing this issue. If someone wants to raise this issue again with more information, please do

**Comment by VincentTam** [comment]
> @VincentTam do you know if there are any updates on staticman? I just checked https://staticman.net/ and there is no mention at all of a v3 API, only v2. If v3 isn't official or recommended yet, I'd like to close this issue

@daattali I'm sorry for my lack of response.  I suffered from game addiction during the lockdown.  Learning C# now, I'm a little bit more active on Git* than before.

As far as I know (about the node.js app one year ago), the idea of a public instance isn't scalable.  When everybody uses it, the it can get "congested".  It's true that the official website has no mention about the newly introduced API variables in v3.  The file `config.js` in the node.js app lists some server-side API variables.  I personally learnt everything from the PR supporting GitLab.

Regarding the question on "recommendation", here's one from the project's maintainer.
> This has been resolved with \#319. We are dropping support for the public Staticman instance and are recommending that all users host their own instance. The simplest way to do this is to click the "Deploy to Heroku" button in the README which will allow you to host your own instance for free without the reliability concerns of using a singular public instance. The public instance will remain running for the time being, though I strongly recommend everyone move away from it.
`https://github.com/eduardoboucas/staticman/issues/317#issuecomment-565250060`
I believe that he, as the maintainer, would recommend a version of the app with recent bug fixes.  Documenting recent changes takes time.  If the maintainer/owner doesn't have the time and effort to do it, and a 3rd-party person doesn't have the energy to test all the features, it's hard for him/her to come up with an encyclopedia-like "documentation".

**Comment by daattali** [comment]
I understand those concerns, but I still would be a little hesitant to use a new version that isn't **at all** mentioned on the official site whatsoever.

**Comment by VincentTam** [comment]
@wini3d @daattali Sorry I'm eating my words again.  Due to the quoted comment from the app's maintainer, I'm going to submit a PR for a README update about the GitHub App setup on a custom Heroku app instance.

I've found the motivation to try out the GitHub App, thanks to a clearly-written blog article https://hajekj.net/2020/04/15/staticman-setup-in-app-service/.  Here's some screenshots showing my successful setup.

* * *

Staticman's README : https://github.com/eduardoboucas/staticman

Click the deploy button inside ![Deploy](https://www.herokucdn.com/deploy/button.svg), and configure the necessary variables in the popped up Heroku page in order to start Staticman with no installation.

![Opera Snapshot_2021-02-01_140133_dashboard heroku com](https://user-images.githubusercontent.com/5748535/106462435-5e021980-6496-11eb-9c60-05471c067bff.png)

![staticman-rsa](https://user-images.githubusercontent.com/5748535/106461761-82a9c180-6495-11eb-95ce-72fd8f11f768.png)  
Screenshot of the `RSA_RPIVATE_KEY` variable.

Successful example: https://github.com/VincentTam/TestStaticmanLab/pull/95

![Screenshot from 2021-02-01 11-36-53](https://user-images.githubusercontent.com/5748535/106447729-21c4be00-6482-11eb-83d9-c200f4a34a83.png)
![Screenshot from 2021-02-01 11-32-49](https://user-images.githubusercontent.com/5748535/106447733-22f5eb00-6482-11eb-99bc-8232cb96f664.png)

* * *

Remarks: If you're using Heroku's online dashboard, simple copy-and-paste the RSA private keys for the config variables `RSA_PRIVATE_KEY` and `GITHUB_PRIVATE_KEY` would do.  There's no need to do the manual replacement of the newline character `\n` with the two-character string `"\n"`.  I tried that in following the linked article and I ran into an `InvalidAsn1Error`.

![screenshot of error](https://user-images.githubusercontent.com/5748535/106450580-a49b4800-6485-11eb-8e85-e3eb75d4b663.png)

After removing all `"\n"` as shown in the screenshot of the text area for `RSA_PRIVATE_KEY` in Heroku's online dashboard, I got pass this error.  The `Set RSA_PRIVATE_KEY` config vars ...` following the green time `09:21:01.49` and the line containing `path="/v3/encrypt/nimportquoi"` at the bottom show that I've successfully fixed the error.
