### ISSUE TITLE
How to display the time of reading on the blog

### ISSUE THREAD

**Issue by memoriesus** [daattali/beautiful-jekyll#593]
Thank you for submitting an issue!

Please only submit bug reports or feature suggestions. Please do not submit support requests and general help questions in this forum.

**Comment by daattali** [comment]
Can you add details of what you mean?

**Comment by memoriesus** [comment]
I mean it can display the time to tell the reader the time you can read it over.

**Comment by daattali** [comment]
That's not a supported feature

**Comment by rubyreads** [comment]
@memoriesus 
There is code that you can add, if you're comfortable doing so. Here is an [example](https://gist.github.com/rubyreads/b1156a4bea4e1d5ed823b87260d410f5). Since it is not a supported feature, you'll have to:
- decide where to place it
- make sure it doesn't conflict with the Beautiful Jekyll theme  

I hope this helps.

**Comment by daattali** [comment]
Thanks @rubyreads ! I'd be happy to add this feature if you want to submit a pull request

**Comment by memoriesus** [comment]
But based on it it's not available to show me the real-time.

**Comment by daattali** [comment]
What do you mean real time?

**Comment by memoriesus** [comment]
I mean  now the code cannot make it happen, perhaps it has a bit bug.

**Comment by daattali** [comment]
I don't understand what you mean. Currently this is not supported. @rubyreads is in the process of adding this feature.

**Comment by daattali** [comment]
Fixed with #622
