### ISSUE TITLE
Syntax highlighter migration

### ISSUE THREAD

**Issue by nakshay** [daattali/beautiful-jekyll#635]
It seems fair to migrate from rouge to PrimsJs for highlighter, Although size maybe an issue but it provides more features and modern look in themes like ```tomorrow night```, it also solves the scrolling issue which rouge has, especially on small devices like cell phones.

I feel below links helpful

[Add primsJS](https://mycyberuniverse.com/replace-rouge-highlighter-prismjs-jekyll.html)
[Disable rouge ](https://mycyberuniverse.com/disable-rouge-syntax-highlighter.html)

**Comment by daattali** [comment]
Thanks @nakshay 

Are there any major issues with rouge? Unless there's a really good reason to switch, I would prefer not to introduce more complexity (an additional javacsript file) for something that already works. I try very hard to keep this theme simple

**Comment by nakshay** [comment]
absolutely agree with you on keeping it simple point. I observed rouge has issues on small screen, like no scrollbar and code wraps but may not be a major issue.

**Comment by nakshay** [comment]
may be you can add notes in readme for those who want to migrate highlighter,  that will help you to keep it simple and help users who want to migrate from rouge.

**Comment by daattali** [comment]
I'm not seeing these issues happening in beautiful jekyll. I addressed the line wrap issue a long time ago by adding CSS to prevent it, so there is horizontal scroll when necessary.

Vertical scroll doesn't exist by default because the code chunk will just be tall - if someone wants to cap the height of the code chunk and add a vertical scroll, it's as simple as adding `pre.highlight { max-height: 300px; }` and that would be enough. If you don't agree and you see these issues still happening with this theme , show me a reproducible example please so I can observe it

**Comment by nakshay** [comment]
I have migrated to prismjs in my fork, but will create a nre repo to reproduce and will share the same.
Thanks

**Comment by nakshay** [comment]
hi @daattali  I tried re-producing scrolling issue, but not able to. 
I think my fork has side effects because I tried to tweak some CSS. 

closing the issue .

**Comment by daattali** [comment]
Either that, or you forked a long time ago before I fixed it.
