### ISSUE TITLE
Using a link the page subtitle causes render issue

### ISSUE THREAD

**Issue by lexicalunit** [daattali/beautiful-jekyll#685]
When I try to add a link to the subtitle of `index.html` I get some weird artifacts that seem to be generated by the code in `head.html`. They appear below the navbar so you can only see them if you go into developer tools and set `.navbar` to be `display: none`.

However on mobile you can see through normal user interaction. Just by trying to scroll up past the header as they will then be pulled down from behind the nav element and into view.

For example, here's the top of my `index.html`:

```html
---
layout: home
title: SpellBot
subtitle: A Discord bot for <a href="https://www.spelltable.com/">SpellTable</a>
---
```

And here is what I see when I visit my site, at the very top, behind the navbar:

![Screen Shot 2020-07-28 at 11 35 05 AM](https://user-images.githubusercontent.com/1903876/88706965-71d35a00-d0c6-11ea-9994-311d97d2686c.png)

Looking at the rendered page source I see:

```html
<body class="vsc-initialized">SpellTable"&gt;
  

  <link rel="alternate" type="application/rss+xml" title="SpellBot - A Discord bot for SpellTable" href="https://lexicalunit.github.io/spellbot/feed.xml">
```

**Comment by daattali** [comment]
I wouldn't expect that to work. The title and subtitle are meant to be plain text. It's very uncommon to use links there so I didn't invest extra time to make that work. Would you like to tackle this issue and try to make links (or any HTML) work in titles?

**Comment by lexicalunit** [comment]
I could definitely take a stab at it if you could point me in the right direction. I was able to trace it to `head.html`, _I think_, but it wasn't obvious to me what was the issue there.

**Comment by daattali** [comment]
The title and subtitle are used in many places, you'd have to do a code search for "title" and "subtitle". They're used in the meta tags of a page, they're used on the feed page, they're used in the blog/page header, they're used when sharing on social media, there are probably other places too. Thinking about it a little more, I think it's be weird to allow HTML , because that would completely throw off and override the UI of the title/subtitle section... I just can't think of an elegant generic way to make it work.

But if you want to try to get it working so that links can work, I would support that.

**Comment by lexicalunit** [comment]
Ohhhh, yeah I see now 🤔 

I guess my use-case is pretty non-typical as I just have the one page and no posts. I may try to hack a solution at some point but it may not be compatible with the goals of this project and might therefore not be able to be merged back in safely. When I do tackle it I will try to make it something you could merge back though 🤞

**Comment by daattali** [comment]
OK. I'm going to close this issue but if you do work on this and have something to merge, feel free to submit a PR
