### ISSUE TITLE
Bug:  Dependency Error: Yikes! It looks like you don't have tzinfo or one of its dependencies installed. In order to use Jekyll as currently configured,

### ISSUE THREAD

**Issue by thomas-gg** [daattali/beautiful-jekyll#705]
When I try to run this website directly cloned as is locally with ruby I run into this error and am not sure how to resolve it.
![image](https://user-images.githubusercontent.com/32282600/90360204-e63b5200-e00f-11ea-8cc6-04d4a74c5887.png)
When I run the command gem install tzinfo and gem install tzinfo-data and then bundle exec jekyll serve I get the exact same error. I run gem check and tzinfo and tzinfo-data are both installed. Anyone have any idea why I can't run locally?
Jekyll serve does not work as well 
![image](https://user-images.githubusercontent.com/32282600/90360299-39ada000-e010-11ea-902c-5ed3ea89dded.png)

**Comment by daattali** [comment]
I'm sorry but I can't help with private help requests as I receive about a dozen each day. This sounds like a generic jekyll issue, there are many online discussion forums for help with jekyll problems. I did notice you said that you were trying to run "this website directly cloned" which generally isn't the right way to use this theme - you either use GitHub diretly (as instructed in the README) or use the methods described [here](https://beautifuljekyll.com/getstarted/#install-steps-hard). Following any one of these methods will work, but to help with your issue is not something I can do.

**Comment by mura94** [comment]
@thomas-gg were you able to solve this?

**Comment by gc1175383875** [comment]
file "beautiful-jekyll-theme.gemspec" add row: 
 spec.add_runtime_dependency "tzinfo-data"

reference
https://github.com/tzinfo/tzinfo/wiki/Resolving-TZInfo::DataSourceNotFound-Errors
