### ISSUE TITLE
Two possible upgrades

### ISSUE THREAD

**Issue by YoniChechik** [daattali/beautiful-jekyll#707]
Great website!! I use it as well at www.AIisMath.com

I have two possible simple upgrades for you:
1. add favicon to head.html:   
```
  <!-- add favicon -->
  <link rel="shortcut icon" type="image/x-icon" href="/aux_assets/favicon.png?">
```
and easily add a flag at the _config for this.

2. possible semi-bug in _includes/header.html 
see my change [here](https://github.com/YoniChechik/AI_is_Math/commit/3c10a30f8546a1a43d410d4b4e24dda4b7e288e5)

**Comment by daattali** [comment]
Shalom Yoni

1. There is an FAQ about how to add a favicon - you just need to add a favicon image to the root and it'll automatically get picked up by jekyll. As far as I know, explicitly using the link tag is only required if you want to use a different location for the image. Is that the reason you're suggesting this, so that the location could be inside assets instead of the root folder? I would be open to a PR that adds the favicon location as a config param, as long as it has a default (even when the config is not available)

2.  Did you notice any bug before making your change? It looks like that line is 5 years old so I don't recall exactly why I did it this way, but that HTML chunk that you placed inside the `else` block is being hidden when there's an image. So visually it ends up being the same as what you did, except that you version removes it from the DOM. I really don't remember if it was just terrible coding on my part 5 years ago or if there was a reason for it...

**Comment by daattali** [comment]
@YoniChechik let me know if you have any more info. I'll close the issue otherwise :)

**Comment by YoniChechik** [comment]
closing

**Comment by ben-nathanson** [comment]
Thank you @YoniChechik! That code snippet resolved a bug where Jekyll wasn't picking up the favicon in the root in my site.

**Comment by daattali** [comment]
@ben-nathanson I'm curious - was your favicon in the root and named `favicon.ico`? If yes, then it really should have worked, I'm not sure what could have prevented it.
