### ISSUE TITLE
Issue in integrating Public Custom LinkedIn URL

### ISSUE THREAD

**Issue by rishabhbanga** [daattali/beautiful-jekyll#71]
## Expected Behavior

Workaround for someone to be able use their Custom LinkedIn Url, instead of the obsolete pub/username/../../...  Url.

## Current Behavior

In _config.yml, you have mentioned to use a format similar to - pub/dean-attali/8/946/143 , to link to LinkedIn, however for a long time now I have been using a Custom Public URL - https://www.linkedin.com/in/rishabhbanga , which is not being properly linked using the current code.

## Solution

Created Pull Request for the same.

**Comment by daattali** [comment]
Thanks @rishabhbanga 

Just so I understand: what if you set the config param to "in/rishabhbanga", doesn't that work?  I was reluctant to change the default URL because I think everybody has a custom URL.  From my understanding, people can opt in to get a custom URL, but it's not universal, right?  Or did LinkedIn recently migrate everyone's account to have a custom URL?  I don't want the URL to be broken for people who don't have the new custom URL

**Comment by rishabhbanga** [comment]
@daattali Even I tried with using "in/rishabhbanga" initially, but it did not work. I agree with the reluctance, and I myself would think it would be better to incorporate both, because as far as I know, the custom URL's are only for those who had themselves modified the URL, but for more or ess everyone the URL is ending with either "in/abc-xxxx" or "in/abc" , where abc is the name and xxxx string of numbers.

**Comment by daattali** [comment]
That's strange, setting the param to "in/name" should work. I just tried it on a test website https://daattalitest.github.io/ and it does seem to work. But I'll accept the PR anyway
