### ISSUE TITLE
Improve PageSpeed score

### ISSUE THREAD

**Issue by JosemyDuarte** [daattali/beautiful-jekyll#711]
I'm not sure on how to properly fix this (I'm mostly backend/DevOps) but I just found these warnings/suggestions while scanning for possible performance issues
<img width="718" alt="Screenshot 2020-08-23 at 21 05 40" src="https://user-images.githubusercontent.com/6247860/90987651-8d763700-e584-11ea-9a34-91f3b133c206.png">

https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fbeautifuljekyll.com%2F

**Comment by daattali** [comment]
Thanks for your comments. These issues are all within normal and I don't think it makes sense to try to remove them. In an ideal environment, where you know the exact content of each page and you have complete control over everything and every ms counts, these things would come into play. Since beautiful jekyll is a template theme, it cannot know which css exactly you use and what to load before vs after.

The CSS files it tells you are being loaded are bootstrap, font awesome icons, google fonts, and beautiful jekyll's own CSS. All of these are indeed needed. If I was creating a single specific website, not a theme, and I would know exactly what content shows above the fold, I could try to be clever and load only specific CSS on page-load and the rest after. But that's not possible with a template. Thanks for bringing it to my attention though
