### ISSUE TITLE
Avatar not loading on home page

### ISSUE THREAD

**Issue by wi5nia** [daattali/beautiful-jekyll#715]
Hi,
in my _config.yaml file I have
```yaml
avatar: "/img/avatar-icon.png"
round-avatar: true
```
The problem is that for whatever reason it doesn't load on the home page https://tomaszwisniewski.com/
When you go into any post you can see that it works https://tomaszwisniewski.com/exam/training/2019/12/09/girls-in-tech-az203.html

The image loads also after going into https://tomaszwisniewski.com/img/avatar-icon.png

No errors in the browser devtools, or while building the site :/ 

Using this theme version
```yaml
remote_theme: daattali/beautiful-jekyll@4.1.0
```

**Comment by daattali** [comment]
Can you show me the code for your website repo? As long as there's an `avatar` config setting and you didn't set `show-avatar=false` in the YAML, it should show up, this doesn't make sense to me. I'd have to see your code to see why this is happening.

**Comment by wi5nia** [comment]
I have invited you to the repo :) @daattali

**Comment by daattali** [comment]
It seems you changed the gem versions in your website, was that on purpose? I can't try to run your website locally to troubleshoot because your website is trying to use jekyl 4.0.1 and I don't have an updated ruby version to support it. GitHub Pages itself is not using jekyll version 4, so I haven't looked into any problems that happen with jekyll 4. Only when GitHub moves to jekyll 4 I'll support it in beautifuljekyll. I honestly don't understand what may have caused this problem, because I looked at the jekyll changelog and it doesn't look like it would break anything, but unfortunately I don't currently support it

**Comment by wi5nia** [comment]
I had a mess with my previous blog installation so I basically migrated...
jekyll new sitename
Added your stuff and that's it so there may be something in the play ... hmm...

**Comment by daattali** [comment]
OK I found the issue.

So simple! In your blog posts, you manually defined `show-avatar` in the YAML. In other pages it wasn't defined. If you use beautifuljekyll via GitHub Pages, then you'd inherit my version of the config file, which set `show-avatar: true` to be the default behaviour , but if you don't have my config then you need to turn it on.

**Comment by wi5nia** [comment]
HA! Good one, added to my index.markdown file

```yaml
show-avatar: true
```

and all is good 😃 thanks!

**Comment by daattali** [comment]
You can do what I did: https://github.com/daattali/beautiful-jekyll/blob/7d784b37c873dcbb7678cd3b2d77f4a494d90b1a/_config.yml#L196-L201

It works this way because up until very recently, I didn't even know how to run sites with ruby, I only knew github pages, so everything was catered to that. Now that I allow people to use their own config files, I should change this so that the default is not done in the config but rather in the code. In the next version you won't have to explicitly say `show-avatar`.
