### ISSUE TITLE
hover or click to open navbar menu?

### ISSUE THREAD

**Issue by CarlosGrohmann** [daattali/beautiful-jekyll#758]
I updated to the latest version from github and now I need to click on the navbar item to open the dropdown menu, but with the old version (from 2018 maybe?) I could open the menu only by hovering over it. Is this the new behavior? Can I change it back to hover?
Thanks for the great theme and dedication

**Comment by daattali** [comment]
You're right, the dropdowns in navbar used to happen on hover and now it's on click. This change was introcued in version 3.0.0 when I migrated to bootstrap 4. Prior to this, the entire navigation bar was constructed manually by me - using a lot of hacky html, javascript, and css. When I migrated to bootstrap 4, I also simplified the codebase a lot and I'm now using bootstrap's own navbar - I kept the same look, but unfortunately their navbar system does not support hover, only click. Maybe they do it so that you'll have consistency across devices (computer vs phone)? I'm not sure why it doesn't support hover , but I decided that the code simplification was worth it. I'm sorry for this unintended consequence.

**Comment by daattali** [comment]
The official bootstrap 4 documentation says: https://getbootstrap.com/docs/4.0/components/dropdowns

> They’re toggled by clicking, not by hovering; this is an [intentional design decision](https://markdotto.com/2012/02/27/bootstrap-explained-dropdowns/).

**Comment by CarlosGrohmann** [comment]
No worries, the change in behavior is minimal and won't be an issue. I'm very happy with the new version. 
thanks
