### ISSUE TITLE
homepage not linked in avatar and site title

### ISSUE THREAD

**Issue by CarlosGrohmann** [daattali/beautiful-jekyll#759]
So I deployed the new version of my website using the last beautiful jekyll, and I got a strange behavior of the avatar (at the center of the window) and the title (to the left). They used to link to the homepage, but now they link to the page I'm at.  
The site can be accessed at http://carlosgrohmann.com/ or https://carlosgrohmann.github.io/  
Using the .com address as an example, if I'm at the start page, both the avatar and the title point to http://carlosgrohmann.com/, but if I'm at another page, like "outreach", they point to http://carlosgrohmann.com/pages/outreach/ and not to http://carlosgrohmann.com/
Did I miss something when upgrading?
Thanks

**Comment by daattali** [comment]
That's strange, I'm not sure why that's happening. Since you had a website before, and you said you're upgrading, how did you do the upgrade? Did you do one of the two methods I describe [here](https://beautifuljekyll.com/faq/#updating)? If you upgraded by taking your existing github repo and selectively modifying files, I would imagine the current situation in the repo is messy. If you upgraded by creating a new repo and this is happening, then I would love to see a minimal reproducible example of how you got this bug to show up.

**Comment by CarlosGrohmann** [comment]
Ok, found it. 
The _config.yml was missing the `url` tag. In the old version there was a "section" for github-pages, not present in this version. Now it points to the correct address (at leas in the .com site, in the github-pages one it points to the .com, since I started using jekyll-scholar and can't use github to build the site anymore).

Thanks for the continuous support and have a great 2021!

**Comment by daattali** [comment]
Great glad it's solved! Please consider supporting if you enjoy this :) https://beautifuljekyll.com/plans/
