### ISSUE TITLE
Feature suggestion: Blog post search bar

### ISSUE THREAD

**Issue by EthanMcBloxxer** [daattali/beautiful-jekyll#770]
A search bar to more easily navigate blog posts could be beneficial when having 4+ pages.
A possible candidate for this could be [Simple-Jekyll-Search](https://github.com/christian-fei/Simple-Jekyll-Search). I've implemented it on my website already and think it would be a good addition to Beautiful Jekyll.

[JSFiddle Demonstration](https://jsfiddle.net/d1h79vsf/) (this is done with liquid and a "search.json" config file, so no results are displayed on the example)
[Live Demonstration](https://ethanmcbloxxer.github.io/beautiful-jekyll/) (a font would be good too)

I already have a forked version of Beautiful Jekyll with this, so I could also submit a PR.

**Comment by daattali** [comment]
Thanks for the suggestion Ethan. It's definitely a nice feature, but I generally try to avoid feature creep and keep the theme simple. If this feature can be incorporated with minimal changes and is very simple for the user to turn on/off - eg. by simply switching a config parameter, then I'd be happy to merge

**Comment by EthanMcBloxxer** [comment]
My strategy was to create "search.html" in includes, then include it in the home layout if `post_search: true` in _config.yml.

**Comment by daattali** [comment]
Done in commit 950c341739a876b0f73de23e59839b42e8869b69

I added a search button to the navbar so that the search will be available on every page and so that it will work even for people who don't use the default `layout: home` homepage, and so that it doesn't take up space in the middle of the page (it didn't seem right to me)

On large screens there's a magnifying glass icon at the end of the navbar:

![image](https://user-images.githubusercontent.com/952340/120118269-98877480-c15f-11eb-9c3f-af5410da387d.png)

On smaller screens with the collapsible menu, that button says "Search":

![image](https://user-images.githubusercontent.com/952340/120118281-ac32db00-c15f-11eb-8cc0-96e082710986.png)

In both cases, an overlay is created that can be closed either by clicking the X button inside the input or the Escape key on the keyboard:

![image](https://user-images.githubusercontent.com/952340/120118329-00d65600-c160-11eb-9e10-9a23366e9ec9.png)
