### ISSUE TITLE
Feature Suggestion: custom-social.html

### ISSUE THREAD

**Issue by Emaleth** [daattali/beautiful-jekyll#786]
Same way we can create and include custom css and js, it would be nice to get same for custom social links, those would appear next to ones built-in to look seamlessly.

**Comment by daattali** [comment]
Are there any social media links that you'd like to add that aren't available? I much prefer adding more sub-items to that list rather than creating an entirely new feature for that

**Comment by Emaleth** [comment]
Oh, in that case: Odysee.com

**Comment by daattali** [comment]
Looks like it may be part of fontawesome soon https://github.com/FortAwesome/Font-Awesome/issues/17320 (you might already know that since you said "yet")

I don't think adding this feature would benefit enough people to warrant adding it - it would involve adding documentation, making code changes, and having one more thing that must be tested every time I make a release. The easiest solution for you would be to take the current social-networks-links.html file and copy it into your project in the same location (in a `_includes` folder), and edit that file to include odysee. You can just add another `<li>` at the end

**Comment by Emaleth** [comment]
Oki, for now will do. Hoping it grows and at some point you will include it.

**Comment by daattali** [comment]
When if you mean "include the icon" then yes I will as soon as it's possible. 

If you mean "include the custom html file" then I don't currently foresee that happening.

I'm closing this issue as resolved. Feel free to open a new issue if you have another request!
