### ISSUE TITLE
Just like page.head-extra, add site.head-extra support for site-wide headers

### ISSUE THREAD

**Issue by kzu** [daattali/beautiful-jekyll#810]
It's useful to be able to add additional `<head>` content site-wide, not just per-page, like the current `page.head-extra`.

**Comment by daattali** [comment]
You can already do this, by adding this parameter as a default value in the config file

Like here https://github.com/daattali/beautiful-jekyll/blob/a531737107167728c5fc8e25a4aadbd65d47533c/_config.yml#L203-L211

**Comment by kzu** [comment]
I'm sorry, not following. I can't figure out what that snippet means and how it allows me to add an extra head site-wide.

Also, it seems quite a bit less discoverable than just introducing the same property at both the site and page level, rather than resorting to an entirely different mechanism for what's essentially the same. 

Just my 2cents :)

**Comment by daattali** [comment]
You can see an extra on my personal site (using footer-extra on all pages)

https://github.com/daattali/daattali.github.io/blob/61e009260efd73cb319d3c952af35cb96ce9582c/_config.yml#L99

I agree that having another explicit parameter for it would be easier, but that would result in a lot of duplications - every single YAML parameter can be duplicated in this way and that's not maintainable. I try to keep the code as clean and simple as possible, to reduce potential bugs.

Perhaps adding a sentence to the README section mentioning that if you want to add a parameter to all pages rather than a single page you can use default values as mentioned in the official jekyll documentation, and follow the example in the config file as an example

https://jekyllrb.com/docs/configuration/front-matter-defaults/

There's a very delicate line I try to walk between having a complete but short and simple readme vs duplicating a lot of the information available in the jekyll docs.

**Comment by kzu** [comment]
I see. But wouldn't that default apply only to *page* headers, meaning non-page layouts wouldn't get it?

**Comment by daattali** [comment]
You can use it on any layout or any page. Read the jekyll documentation I linked to. It can be used on any page

**Comment by kzu** [comment]
What I'm saying is that the cognitive leap from just another property that matches the page-level one (that's from *your* template, not jekyll) vs going "all in" jekyll is a bit much. Sure, I understand that Jekyll can do everything (and more :)), but I thought the point of your template and your added properties was to simplify that process and offer a somewhat more "higher level" abstraction/configuration on top.

Anyway, I'm using this from my fork, so feel free to disregard and close.

Thanks!

**Comment by daattali** [comment]
[What I linked to on my personal site](https://github.com/daattali/daattali.github.io/blob/61e009260efd73cb319d3c952af35cb96ce9582c/_config.yml#L99) is actually an example of using the parameter on ALL pages, regardless of the layout 

To clarify: *any* of the page-specific options can be used site-wide by using the "default" section in the config file. I agree that the average user may not know that, so I think adding a sentence about that would be useful.

But there is already a very long list of options/parameters and I'm very conscious about not proving a laundry list of options that gets out of hand. So if something is already supported and takes 2 more lines in the config file, I prefer to document that rather than add a new option for it.

**Comment by kzu** [comment]
Makes sense, nuked my changes!
