### ISSUE TITLE
jekyll 3.9.1 | Error:  no implicit conversion of Hash into Integer

### ISSUE THREAD

**Issue by barun108** [daattali/beautiful-jekyll#843]
I am getting this error on local run

> `jekyll 3.9.1 | Error:  no implicit conversion of Hash into Integer`

**Comment by daattali** [comment]
Hi @barun108 unfortunately I cannot provide support for local installation issues. This theme is mostly meant to be a GitHub Pages theme, and the local installation instructions are a DIY with no support because every system is different and can have its own specific issues. I suggest asking for help in jekyll forums that have thousands of users who might be able to help

**Comment by rusty-snake** [comment]
Hi, I had the same issues and could solve it by installing ruby 2.7 (rather than 3.0).

https://blog.kagesenshi.org/2021/05/ruby24-fedora34.html
https://bbs.archlinux.org/viewtopic.php?id=265534
