### ISSUE TITLE
Where to modify css for tables?

### ISSUE THREAD

**Issue by angoodkind** [daattali/beautiful-jekyll#893]
I would like to add a table in one of my regular pages, but without a header. For example, I've found the code and css below. Which css file would I add this to?

```
| Item | Description | Price |
| --- | --- | ---: |
| item1 | item1 description | 1.00 |
| item2 | item2 description | 100.00 |
{:.mbtablestyle}

.mbtablestyle {
    border-collapse: separate;
    empty-cells: hide;

   > table, td, th {
        border: 1px solid black;
        }
}
```

Thanks!

**Comment by angoodkind** [comment]
Maybe I'm using an older version, but I don't see this option. At the bottom of my `_config.yml` file it says `2fc73a3a967e97599c9763d05e564189`. Is that a version num?

**Comment by daattali** [comment]
Here it the line in the current version https://github.com/daattali/beautiful-jekyll/blob/5180092c45a71ab74e5b4fade01748555eb474e5/_config.yml#L126

If you don't see this parameter in your config then yes your version is too old. In that case you can use the `css` YAML frontmatter parameters (that was around since day 1)
