### ISSUE TITLE
Navbar-brand not working

### ISSUE THREAD

**Issue by buildwithdan** [daattali/beautiful-jekyll#954]
Hi guys,

Seem to run into an issue; when I click on the "my website" on the far left OR the icon at the top of the page, they dont seem to take you back to the homepage. Any idea how to fix this? I tried going through the nav.html but struggling to piece it together.

Any thoughts would be greatly appreciated!

**Comment by buildwithdan** [comment]
want to add that I found this code to be missing on the nav.html

    <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

I assume this is

**Comment by daattali** [comment]
Please share your website and link to the code if you believe there's a bug

**Comment by OZ7UP** [comment]
[https://github.com/daattali/beautiful-jekyll/issues/794#issuecomment-951227066](url)

Depending on what you are using to deploy your site, this should be able to help. I had a similar issue, but was able to fix it by applying this as a solution.

I'd do a PR, but most of the changes I've also made to the file are quite personal, and I don't want to risk pushing _my stuff_ to the original repository. Perhaps someone else might be willing to set up a new "Beautiful Jekyll" page to apply this particular fix so that they can request to merge it?

**Comment by daattali** [comment]
@buildwithdan please let us know more details about when this issue happens for you
