### ISSUE TITLE
Issue with category generation

### ISSUE THREAD

**Issue by vietanhdev** [daattali/beautiful-jekyll#98]
@daattali 
hello. Firstly, thank you for your beautiful theme.
I'm building my site at [vietanhdev.github.io](https://github.com/vietanhdev/vietanhdev.github.io).
I used some code for generating category site ([categories.html](https://github.com/vietanhdev/vietanhdev.github.io/blob/issue/categories.html) file). It worked perfectly. But after I added tags in my posts, it only showed one post per category or tag. It also removed my titles, changed my post date. 

Branch having this issue: [https://github.com/vietanhdev/vietanhdev.github.io/tree/issue](https://github.com/vietanhdev/vietanhdev.github.io/tree/issue
)

 I'm new in Jekyll. Can you help me to fix this?

**Comment by daattali** [comment]
It's very hard for me to debug what's going on in your project because I see you have a lot of commits and aren't pointing me to a single file/line/issue. Category generation only works if you build jekyll locally on a webserver.  You can set the date and title of a page explicitly using the `title` and `date` YAML parameters in every post. I'm not sure how much stuff you changed in your repo, but if you use exactly the files from beautiful jekyll then category generation should work fine. If it isn't working for you then just copy those files again from my repo, I unfortunately don't have time to help you debug your custom changes

**Comment by vietanhdev** [comment]
Thank you for looking into my problem. I've fixed it by rewriting all categories and tags name.
